### ISSUE TITLE
RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods helpwanted and medivalmusic

### ISSUE THREAD

**Issue by AHartTN** [StrikerRockers-Mods/SBM-Jukebox-fabric#1]
This mod's mixin name conflicts with a number of different mods (TerrariaPaintings, Medieval Music, Help Wanted, etc.)

**Comment by strikerrocker** [comment]
Sorry for taking too long.

**Comment by AHartTN** [comment]
If that's to me, no worries friend. Thanks for writing mods for Minecraft =P
